services:
  db:
    image: postgres:14-alpine
    container_name: inmohouse_db
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=inmohouse
    ports:
      - '5435:5432'
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: